### ISSUE TITLE
Use this breakout board as uart passthrough to use Dynamixel Wizard config interface?

### ISSUE THREAD

**Issue by bombarie** [JosueAGtz/dynamixelInterface#2]
Am starting to learn about Dynamixel motors through working with your board. Thank you so much for designing this, if it ends up working as expected it's a magic bullet in this microcontroller ecosystem!

I fabricated and assembled this pcb myself (would have totally bought from you, but you were out!) and it appears to work. I have a few Dynamixel XL motors that have already been used, so I don't know exactly what config they have. I can't get the motors to spin yet, although it appears that I can read their ID and MotorPosition so it looks like I do have the right baudrate and dxl protocol selected. 

I see that there is a handy desktop-based Dynamixel Wizard program that handles a lot of troubleshooting and config tasks, but I'm not sure how I would use that program with my esp32 + dxl breakout board setup. Would I have to write a special kind of Serial passthrough sketch, passing incoming Serial data to the dxlSerial? Have you used Dynamixel Wizard with your board?

**Comment by JosueAGtz** [comment]
Hi Bombarie, the Dynamixel interface can be connected directly to the PC or your ESP32 microcontroller, I have designed this interface especially to use with a microcontroller so I don't recommend using the Dynamixel wizard for other things than configuring your motor, for controlling and using the motor feedback you should use your microcontroller. There is nothing that you can't do with the microcontroller that you do with the Dynamixel Wizard, you can download the Arduino library to start communicating with your motors directly from the ESP32 and the Arduino IDE.

I have designed an ESP32 Dynamixel configurator to have an option for a portable configurator, so there is no restriction to use the motors. (I have not released this code yet as I have the intention of building a complete prototype before )

![smartConfig](https://github.com/JosueAGtz/dynamixelInterface/assets/86976466/cc48413e-c392-4b31-af29-4756a0d2d190)

![WhatsApp Image 2024-04-24 at 8 44 08 AM](https://github.com/JosueAGtz/dynamixelInterface/assets/86976466/34288b82-2545-4a2a-857b-24a8c12b5554)

So you can have the interface working directly with your ESP32 without having to use the Dynamixel Wizard or vice-versa. If you were to use both I would recommend having two independent USB-Serial converters, one for the Dynamixel Interface and the other connected to the ESP32.

**Comment by bombarie** [comment]
Hi @JosueAGtz , thanks for your reply. Okay, I can see that I should be able to config everything using just the ESP32, the visual frontend of the Dynamixel Wizard just seemed more convenient. In the meantime I have a little 'progress'. As mentioned I was able to _read_ a Dynamixel motor (XL430), but I just wasn't able to _tell_ the motor to do something with your library. The [Dynamixel2Arduino](https://github.com/ROBOTIS-GIT/Dynamixel2Arduino) library however, did allow me to achieve that (using your breakout board). I would rather continue using your library though, any ideas of what I might be missing? This is a vague question I agree, but I don't see what else might be wrong on my end. I'm telling the library to talk to the motor using 57600 baudrate, dxl protocol v2.0, and correct motor id.... but no reaction when telling it to move. Thoughts?

ps : your ESP32 Dynamixel configurator looks awesome :)

**Comment by JosueAGtz** [comment]
It is very important to configure the motor Mode before trying to move a Dynamixel with Protocol 2.0, you will need to set the operation mode of your Dynamixel to Position Control or Similar depending on your desired control mode, a basic configuration will look like the following:

```
  Dynamixel.setTorque( DXL_ID, OFF);
  Dynamixel.setOperationMode(DXL_ID, POSITION_CTRL);
  Dynamixel.setProfileVelocity(DXL_ID, 0);
  Dynamixel.setTorque( DXL_ID, ON);
```

When profileVelocity is set to 0 the motor will move at maximum speed, you can try using the following basic move example for protocol 2.0 with your Dynamixel, just set the correct ID, Direction Pin, and UART(Serial) Port. 

```
#include <Dynamixel.h>

#define DXL_BAUDRATE    57600
#define DXL_SERIAL      dxlSerial
#define DXL_PROTOCOL    2
#define DXL_DIR_PIN     37

#define DYNARESOLUTION  4096
#define MAXPOSITION     4000
#define MINPOSITION     100
#define OFFSET          10

HardwareSerial dxlSerial(0);

const uint8_t DXL_ID = 1;

short Position;
String motorModel;

void setup() {

  dxlSerial.begin(DXL_BAUDRATE, SERIAL_8N1, RX, TX);  // Define your RX and TX pins "Feather S3 44-RX 43-TX"
  Serial.begin(115200);                               // initialize serial communication at 115200 bps, Enable CDC on Boot

  Dynamixel.begin(&dxlSerial, DXL_BAUDRATE, DXL_DIR_PIN, DXL_PROTOCOL);
  delay(1000);
  
  Dynamixel.setTorque( DXL_ID, OFF);
  Dynamixel.setOperationMode(DXL_ID, POSITION_CTRL);
  Dynamixel.setProfileVelocity(DXL_ID, 0);
  Dynamixel.setTorque( DXL_ID, ON);
            
  Dynamixel.move(DXL_ID, MINPOSITION);
}

void loop() {

  Position = Dynamixel.readPosition(DXL_ID);
  motorModel = Dynamixel.mapMotorModel((Dynamixel.readModel(DXL_ID)));

  Serial.print(motorModel);
  Serial.print(" -> Position: "); Serial.print((Position * 360) / DYNARESOLUTION);
  Serial.println("°.");

  if ((Dynamixel.readPosition(DXL_ID) > MAXPOSITION - OFFSET) && (Dynamixel.readPosition(DXL_ID) < MAXPOSITION + OFFSET))
    Dynamixel.move(DXL_ID, MINPOSITION);

  if ((Dynamixel.readPosition(DXL_ID) > MINPOSITION - OFFSET) && (Dynamixel.readPosition(DXL_ID) < MINPOSITION + OFFSET))
    Dynamixel.move(DXL_ID, MAXPOSITION);

  delay(100);

}
```

Regards

**Comment by bombarie** [comment]
Oh my, I did not realize that that motor mode configuration was necessary. If could helps noobs like me to add that to your examples. The above sketch now works for me. Hooray!

**Comment by JosueAGtz** [comment]
I have now updated the moveServo example to add those code lines when using Dynamixel Protocol 2.0
